# Generated by Django 4.0 on 2021-12-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Name')),
                ('comm', models.CharField(blank=True, max_length=150, verbose_name='Communication')),
                ('mess', models.TextField(blank=True, verbose_name='Message')),
                ('data', models.TimeField(auto_now_add=True)),
                ('colled', models.BooleanField(blank=True, verbose_name='Coll status')),
                ('my_comment', models.TextField(blank=True, verbose_name='My comment')),
            ],
        ),
    ]
